# --- One-time setup & environment recipes ---

secret_scope := if have_dev_config == "true" { `python -c "import json; print(json.load(open('.dev/init-config.json'))['secret_scope'])"` } else { "pr-quiz" }
secret_key_github := "github_token"

# Regenerate .just/shell.justfile for this platform
[script]
[group: 'setup']
bootstrap:
  mkdir -p .just;
  if [ "{{os_family()}}" = "windows" ]; then
    bash_path="C:/Program Files/Git/bin/bash.exe";
  else
    bash_path="bash";
  fi
  {
    echo "# --- AUTO-GENERATED by \`just bootstrap\` -- do not edit ---";
    echo "set shell := [\"$bash_path\", \"-euo\", \"pipefail\", \"-c\"]";
    echo "set script-interpreter := [\"$bash_path\", \"-euo\", \"pipefail\"]";
  } > .just/shell.justfile
  echo "wrote .just/shell.justfile"

# Verify required tooling is installed and authenticated
[script]
[group: 'setup']
setup: bootstrap
  for tool in databricks gh python just; do
    if ! command -v "$tool" > /dev/null; then echo "MISSING: $tool"; exit 1; fi
  done
  databricks current-user me --profile {{profile}} -o json | python -c "import json,sys; print('databricks:', json.load(sys.stdin)['userName'])";
  echo "setup OK"

# Create UC tables from the rendered init_tables.sql (idempotent)
[group: 'setup']
init-tables: require-dev-config render
  python {{bundle_dir}}/scripts/sql_exec.py --file {{bundle_dir}}/sql/init_tables.sql --warehouse-id {{warehouse_id}} --profile {{profile}}

# NOTE: canonical path is `python installer/pr_quiz_install.py backend` (step 2); this
# recipe stays as a dev convenience because it scrapes the token from git credentials.
# Store the repo-pinned GitHub token in the Databricks secret scope for the generation job
[script]
[group: 'setup']
put-github-secret: require-dev-config
  token=$(printf 'protocol=https\nhost=github.com\n' | git credential fill | grep '^password=' | cut -d= -f2);
  if [ -z "$token" ]; then echo "no pinned GitHub credential found"; exit 1; fi
  databricks secrets put-secret {{secret_scope}} {{secret_key_github}} --string-value "$token" --profile {{profile}};
  echo "secret {{secret_scope}}/{{secret_key_github}} updated"

# NOTE: canonical path is `python installer/pr_quiz_install.py backend` (step 5), which
# also mints the OAuth secret via the CLI; kept for this repo's ops (.ci-sp-client-id file).
# Create the CI service principal + OAuth secret for GitHub Actions (prints UI fallback on failure)
[script]
[group: 'setup']
create-ci-sp:
  set +e;
  sp=$(databricks service-principals create --display-name pr-quiz-ci --profile {{profile}} -o json);
  status=$?;
  set -e;
  if [ "$status" -ne 0 ]; then
    echo "CLI creation failed - create manually: Settings > Identity and access > Service principals";
    echo "then generate an OAuth secret on the SP page and add GitHub repo secrets:";
    echo "  DATABRICKS_HOST / DATABRICKS_CLIENT_ID / DATABRICKS_CLIENT_SECRET";
    exit 1;
  fi
  echo "$sp" | python -c "import json,sys; sp=json.load(sys.stdin); print('client_id:', sp['applicationId']); open('.ci-sp-client-id','w').write(sp['applicationId'])";
  echo "SP created. Generate OAuth secret: Settings > Identity and access > Service principals > pr-quiz-ci > Secrets";
  echo "then: gh secret set DATABRICKS_HOST / DATABRICKS_CLIENT_ID / DATABRICKS_CLIENT_SECRET"

# NOTE: canonical path is `python installer/pr_quiz_install.py backend` (step 6), which
# ports this exact grants sequence; kept for this repo's ops.
# Grant table + bundle-folder access to the app SP and CI SP (run after first deploy)
[script]
[group: 'setup']
grants: require-dev-config render
  app_sp=$(databricks apps get {{app_name}} --profile {{profile}} -o json | python -c "import json,sys; print(json.load(sys.stdin)['service_principal_client_id'])");
  echo "app SP: $app_sp";
  python {{bundle_dir}}/scripts/sql_exec.py --statement "GRANT USE CATALOG ON CATALOG workspace TO \`$app_sp\`" --warehouse-id {{warehouse_id}} --profile {{profile}};
  python {{bundle_dir}}/scripts/sql_exec.py --statement "GRANT USE SCHEMA, SELECT, MODIFY ON SCHEMA workspace.pr_quiz TO \`$app_sp\`" --warehouse-id {{warehouse_id}} --profile {{profile}};
  # App deployments staged by the app SP read bundle source from the deploying user's
  # home; without CAN_READ a CI-SP-initiated app start fails with "no files found".
  me=$(databricks current-user me --profile {{profile}} -o json | python -c "import json,sys; print(json.load(sys.stdin)['userName'])");
  ws_bundle_dir="/Users/$me/.bundle/{{project_name}}";
  dir_id=$(MSYS_NO_PATHCONV=1 databricks workspace get-status "$ws_bundle_dir" --profile {{profile}} -o json | python -c "import json,sys; print(json.load(sys.stdin)['object_id'])");
  acl="{\"service_principal_name\":\"$app_sp\",\"permission_level\":\"CAN_READ\"}";
  if [ -f .ci-sp-client-id ]; then
    acl="$acl,{\"service_principal_name\":\"$(cat .ci-sp-client-id)\",\"permission_level\":\"CAN_READ\"}";
  fi
  databricks workspace update-permissions directories "$dir_id" --json "{\"access_control_list\":[$acl]}" --profile {{profile}} > /dev/null;
  echo "bundle folder CAN_READ granted on $ws_bundle_dir";
  if [ -f .ci-sp-client-id ]; then
    ci_sp=$(cat .ci-sp-client-id);
    echo "CI SP: $ci_sp";
    python {{bundle_dir}}/scripts/sql_exec.py --statement "GRANT USE CATALOG ON CATALOG workspace TO \`$ci_sp\`" --warehouse-id {{warehouse_id}} --profile {{profile}};
    python {{bundle_dir}}/scripts/sql_exec.py --statement "GRANT USE SCHEMA, SELECT ON SCHEMA workspace.pr_quiz TO \`$ci_sp\`" --warehouse-id {{warehouse_id}} --profile {{profile}};
    databricks warehouses update-permissions {{warehouse_id}} --json "{\"access_control_list\":[{\"service_principal_name\":\"$ci_sp\",\"permission_level\":\"CAN_USE\"}]}" --profile {{profile}} > /dev/null;
    job_id=$(databricks jobs list --name {{job_name}} --profile {{profile}} -o json | python -c "import json,sys; print(json.load(sys.stdin)[0]['job_id'])");
    databricks jobs update-permissions "$job_id" --json "{\"access_control_list\":[{\"service_principal_name\":\"$ci_sp\",\"permission_level\":\"CAN_MANAGE_RUN\"}]}" --profile {{profile}} > /dev/null;
    databricks apps update-permissions {{app_name}} --json "{\"access_control_list\":[{\"service_principal_name\":\"$ci_sp\",\"permission_level\":\"CAN_MANAGE\"}]}" --profile {{profile}} > /dev/null || echo "app permission grant failed - grant CAN_MANAGE via UI";
  else
    echo "no .ci-sp-client-id - run 'just create-ci-sp' first, then re-run grants";
  fi
  echo "grants done"
